name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nrfmicro_13
            shield: the_paintbrush_right
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Prepare variables
        id: variables
        run: |
          if [ -n "${{ matrix.shield }}" ]; then
            SHIELD_ARG="-DSHIELD=${{ matrix.shield }}"
            ARTIFACT_NAME="${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey"
          else
            SHIELD_ARG=
            ARTIFACT_NAME="${{ matrix.board }}-zmk-artsey"
          fi
          echo ::set-output name=shield-arg::${SHIELD_ARG}
          echo ::set-output name=artifact-name::${ARTIFACT_NAME}
      - name: Build (west build)
        run: west build -s zmk/app -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: ARTSEY implementation dtsi file
        if: always()
        run: cat -n config/artsey.dtsi
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/${{ matrix.board }}.dts.pre.tmp
      - name: Prep artifact (artsey.dtsi)
        run: cp config/artsey.dtsi ./artsey.dtsi
      - name: Prep artifact (${{ matrix.shield }}-${{ matrix.board }}.dts.pre.tmp)
        run: cp build/zephyr/${{ matrix.board }}.dts.pre.tmp ./${{ matrix.shield }}-${{ matrix.board }}.dts.pre.tmp
      - name: Prep artifact (${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.hex)
        run: cp build/zephyr/zmk.hex ${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.hex
      - name: Prep artifact (${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.uf2)
        run: cp build/zephyr/zmk.uf2 ${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.uf2
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: '${{ steps.variables.outputs.artifact-name }}'
          path: |
            artsey.dtsi
            ${{ matrix.shield }}-${{ matrix.board }}.dts.pre.tmp
            ${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.hex
            ${{ matrix.shield }}-${{ matrix.board }}-zmk-artsey.uf2
        continue-on-error: true
